### ISSUE TITLE
Name error

### ISSUE THREAD

**Issue by AviatorFuchs** [Styunlen/Styunlen-s-Minecrafr-Server-Status-GUI#2]
Styunlen-s-Minecrafr-Server-Status-GUI

Styunlen-s-Minecraft-Server-Status-GUI

**Comment by Styunlen** [comment]
**Sorry for that I didn't optimize the support of multi languages**

**However, something I need to talk to you is that due to the resumption of study in 2 days,I probably do not have time to fix up some problem of this project for at least 1 month(I‘m learning at boarding school).So I will try my best to fix up your problem during the rest of two days.If I do not fix it in two days,forgive me for my busy study.**

**At last, forgive my poor English level.More than delighted for the issue you created.**

**Comment by Styunlen** [comment]
I'will be grateful that you would give me more details of this issue
